In [214]:
%matplotlib inline

import numpy as np
from sklearn.model_selection import train_test_split
from pylab import *
import pandas as pd
from sklearn import linear_model

df = pd.read_csv("inter2.csv")

In [275]:
## For extracting the features from the csv file

import csv
import sys

f = open("inter2.csv", "rb")
reader = csv.reader(f)
target=[]
k=0
for row in reader:
    if(k>0):
        temp=[]
        for i in row[1:7]:
            temp.append(int(i))
        target.append(temp)
    k+=1    

print target

[[3, 3, 3, 3, 3, 3], [3, 3, 3, 3, 3, 2], [3, 3, 3, 3, 2, 3], [3, 1, 3, 3, 3, 3], [3, 3, 3, 3, 1, 1], [3, 3, 3, 3, 3, 3], [3, 3, 3, 3, 3, 3], [3, 3, 3, 3, 3, 3], [3, 3, 3, 2, 1, 1], [3, 3, 3, 2, 1, 1], [3, 3, 3, 3, 3, 3], [3, 3, 3, 3, 3, 3], [1, 1, 1, 1, 1, 1], [2, 2, 3, 3, 1, 1], [3, 2, 3, 3, 1, 1], [3, 3, 3, 3, 1, 1], [3, 3, 3, 3, 3, 3], [3, 3, 3, 1, 2, 2], [3, 3, 3, 1, 1, 1], [3, 3, 3, 1, 1, 1], [3, 3, 3, 1, 1, 1], [2, 3, 3, 3, 3, 2], [3, 3, 3, 1, 1, 1], [3, 3, 3, 1, 1, 1], [3, 3, 3, 3, 1, 1], [2, 3, 3, 1, 2, 1], [3, 3, 3, 3, 3, 3], [3, 3, 3, 3, 3, 3]]


In [199]:
## Forr opening that file

import pickle
f=open('text_answer.txt','r')
new_text=pickle.load(f)

In [200]:
## For storing variables in a data file as text format

import pickle
f=open('text_answer.txt','w')
pickle.dump(text,f)
f.close()

In [201]:
new_text[1]=new_text[1].replace("  "," ")

In [202]:
"Hello. And".split(" ")

['Hello.', 'And']

In [204]:
import nltk
res=nltk.pos_tag(new_text[1].split(" "))
print res

[('So', 'RB'), ('challenge', 'JJ'), ("I've", 'NNP'), ('overcame', 'NN'), ('was', 'VBD'), ('having', 'VBG'), ('a', 'DT'), ('primarily', 'RB'), ('business', 'NN'), ('backgrounds', 'NNS'), ('and', 'CC'), ('coming', 'VBG'), ('into', 'IN'), ('completely', 'RB'), ('technology-based', 'JJ'), ('company,', 'NN'), ('kind', 'NN'), ('of', 'IN'), ('like', 'IN'), ('finding', 'VBG'), ('a', 'DT'), ('role', 'NN'), ('for', 'IN'), ('myself', 'PRP'), ('and', 'CC'), ('being', 'VBG'), ('able', 'JJ'), ('to..', 'NN'), ('It', 'PRP'), ('was', 'VBD'), ('kind', 'NN'), ('of', 'IN'), ('hard', 'JJ'), ('because', 'IN'), ('I', 'PRP'), ('had', 'VBD'), ('to', 'TO'), ('kind', 'NN'), ('of', 'IN'), ('learn', 'NN'), ('all', 'PDT'), ('those', 'DT'), ('new', 'JJ'), ('things', 'NNS'), ('and', 'CC'), ('not', 'RB'), ('even', 'RB'), ('just', 'RB'), ('ffrom', 'VB'), ('being', 'VBG'), ('able', 'JJ'), ('to', 'TO'), ('do', 'VB'), ('them', 'PRP'), ('but', 'CC'), ('being', 'VBG'), ('able', 'JJ'), ('to', 'TO'), ('understand', 'VB'), ('h

In [205]:
tags_list=[0]*len(res)
for i in range(len(res)):
    tags_list[i]=res[i][1]
print tags_list


['RB', 'JJ', 'NNP', 'NN', 'VBD', 'VBG', 'DT', 'RB', 'NN', 'NNS', 'CC', 'VBG', 'IN', 'RB', 'JJ', 'NN', 'NN', 'IN', 'IN', 'VBG', 'DT', 'NN', 'IN', 'PRP', 'CC', 'VBG', 'JJ', 'NN', 'PRP', 'VBD', 'NN', 'IN', 'JJ', 'IN', 'PRP', 'VBD', 'TO', 'NN', 'IN', 'NN', 'PDT', 'DT', 'JJ', 'NNS', 'CC', 'RB', 'RB', 'RB', 'VB', 'VBG', 'JJ', 'TO', 'VB', 'PRP', 'CC', 'VBG', 'JJ', 'TO', 'VB', 'WRB', 'PRP', 'VBP', 'WRB', 'DT', 'VBZ', 'TO', 'DT', 'NN', 'CC', 'RB', 'RB', 'RB', 'NNP', 'VBG', 'NN', 'NN', 'RB', 'RB', 'VBZ', 'PRP$', 'NNS', 'IN', 'PRP', 'CC', 'IN', 'NNP', 'VBD', 'NN', 'IN', 'DT', 'JJ', 'NN', 'PRP', 'VBP', 'VB', 'DT', 'NN', 'NN', 'WP', 'VBZ', 'RB', 'RB', 'JJ', 'IN', 'VBG', 'JJ', 'JJ', 'RB', 'JJ', 'CC', 'RB', 'WRB', 'PRP', 'IN', 'NNP', 'VBG', 'PRP$', 'NN', 'IN', 'CD', 'NN', 'VBG', 'JJ', 'JJ', 'NNS', 'CC', 'JJ', 'NN', 'PRP', 'RP', 'PRP', 'VBP', 'TO', 'PRP', 'CC', 'VB', 'NN', 'NN', 'DT', 'VBZ', 'WP', 'NNP', 'VBD', 'JJ', 'NN', 'DT', 'VBZ', 'WP', 'NNP', 'NN', 'NNP', 'PRP', 'JJ', 'CC', 'JJ', 'VBN', 'RB', 'J

In [222]:
tags_list=list(sorted(set(tags_list)))
print tags_list

['CC', 'CD', 'DT', 'IN', 'JJ', 'NN', 'NNP', 'NNS', 'PRP', 'PRP$', 'RB', 'RP', 'TO', 'VB', 'VBD', 'VBG', 'VBN', 'VBZ', 'WDT', 'WP', 'WRB']


In [223]:
t=['EX','FW','JJR','JJS','LS','MD','NNPS','PDT','POS','RBR','RBS','SYM','UH','VBP','WP$','WDT',',']

In [228]:
tags_final=sorted([',','CC', 'CD', 'DT', 'EX', 'FW', 'IN', 'JJ', 'JJR', 'JJS', 'LS', 'MD', 'NN', 'NNP', 'NNPS', 'NNS', 'PDT', 'POS', 'PRP', 'PRP$', 'RB', 'RBR', 'RBS', 'RP', 'SYM', 'TO', 'UH', 'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ', 'WDT', 'WP', 'WP$', 'WRB']) 
print tags_final

[',', 'CC', 'CD', 'DT', 'EX', 'FW', 'IN', 'JJ', 'JJR', 'JJS', 'LS', 'MD', 'NN', 'NNP', 'NNPS', 'NNS', 'PDT', 'POS', 'PRP', 'PRP$', 'RB', 'RBR', 'RBS', 'RP', 'SYM', 'TO', 'UH', 'VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ', 'WDT', 'WP', 'WP$', 'WRB']


In [232]:
import collections

inputs = []

for text in new_text:
    
    #print text
    text = text.strip()
    text=text.replace("  "," ")
    
    #print(len(nltk.pos_tag(text.split(" "))))
    res=nltk.pos_tag(text.split(" "))
    
#     print res
    p=len(res)
    #print p
    tags_list=[0]*p
    for j in range(p):
        tags_list[j]=res[j][1]

    tags =collections.OrderedDict()
    for k in range(len(tags_final)):
        tags[tags_final[k]] = 0


    for l in range(len(tags_list)):
        tags[tags_list[l]]+=1
        
    inputs.append(tags.values())
    #print(tags.values())
    
print len(inputs)



28


In [274]:
len(target)

27

In [238]:
import pickle
f=open('input_features.txt','w')
pickle.dump(inputs,f)
f.close()

In [237]:
len(inputs[27])

37

In [ ]:
#nltk.download('tagsets')

In [ ]:
#nltk.download('averaged_perceptron_tagger')

In [ ]:
df.head()


In [ ]:
text = df["Transcription"]
print text

In [ ]:
#quantify answer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction import DictVectorizer
from scipy.sparse import hstack

# For beginning, transform train['FullDescription'] to lowercase using text.lower()
df['Transcription'].str.lower()

# Then replace everything except the letters and numbers in the spaces.
# it will facilitate the further division of the text into words.
df['Transcription'].replace('[^a-zA-Z0-9]', ' ', regex = True)

# Convert a collection of raw documents to a matrix of TF-IDF features with TfidfVectorizer
vectorizer = TfidfVectorizer(min_df=5)
X_tfidf = vectorizer.fit_transform(df['Transcription'])

print X_tfidf


In [292]:
#split to test data
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.neural_network import MLPClassifier


X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.25, random_state=42)


In [293]:
len(y_train[0])

6

In [297]:
# fit a model
lm =  linear_model.LinearRegression()
lm.fit(X_train, y_train)
predictions = lm.predict(X_test)
print(predictions)

# error
error=np.mean(abs(predictions-y_test))
print"Error is ",error

[[ 2.98497962  2.97800872  3.          3.53928708  2.13299474  2.61462144]
 [ 2.82914253  3.05647585  3.          3.54088512  2.59957144  3.11639111]
 [ 2.90782314  3.13987157  3.          0.81053293  1.59793785  1.75499517]
 [ 2.01002703  3.09867721  3.         -0.63784978  3.38037693  3.24340966]
 [ 2.88513678  5.39147095  3.          2.68093078  3.76879032  3.77087388]
 [ 3.27380266  3.23912789  3.          2.69611816  2.00022132  1.79510593]
 [ 2.85171652  2.81565343  3.          2.38140763  1.05775944  1.12826948]]
Error is  0.869252914645648


In [ ]:
lm.predict(feature_values)

In [304]:
for i in range(len(predictions)):
    for j in range(len(predictions[i])):
        predictions[i][j]=round(predictions[i][j])

In [300]:
import math
math.ceil(predictions[0])

TypeError: only size-1 arrays can be converted to Python scalars

In [305]:
# error
error=np.mean(abs(predictions-y_test))
print"Error is ",error

Error is  0.8809523809523809


In [306]:
predictions

array([[ 3.,  3.,  3.,  4.,  2.,  3.],
       [ 3.,  3.,  3.,  4.,  3.,  3.],
       [ 3.,  3.,  3.,  1.,  2.,  2.],
       [ 2.,  3.,  3., -1.,  3.,  3.],
       [ 3.,  5.,  3.,  3.,  4.,  4.],
       [ 3.,  3.,  3.,  3.,  2.,  2.],
       [ 3.,  3.,  3.,  2.,  1.,  1.]])

In [308]:
y_test


[[3, 3, 3, 2, 1, 1],
 [2, 3, 3, 1, 2, 1],
 [3, 3, 3, 2, 1, 1],
 [2, 3, 3, 3, 3, 2],
 [3, 3, 3, 3, 3, 3],
 [1, 1, 1, 1, 1, 1],
 [3, 3, 3, 1, 2, 2]]

In [311]:
t=abs(predictions-y_test)
print t

[[0. 0. 0. 2. 1. 2.]
 [1. 0. 0. 3. 1. 2.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 4. 0. 1.]
 [0. 2. 0. 0. 1. 1.]
 [2. 2. 2. 2. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [312]:
sum(t)

37.0

In [316]:
f=37.0/(6*7)

In [317]:
f

0.8809523809523809